Radio component
funda-frontend/ui pull request #142
Opened 2020-11-12 15:15 UTC by renancarvalho

Add Radio button

I did the 'complicated' selectors using pure css. I didn't not figured how to do that with tailwind. Maybe someone could help on that, although I think this is something also to be discussed once it will add some complexity for something simple.

Let me know what you think!

2020-11-12 15:28 UTC, dine commented on src/components/ui-radio.vue
> +                <img
Can we use a div here? The img tag creates a weird shape (not super round) in all browsers.

2020-11-12 16:54 UTC, larsdouweschuitema requested changes
Nice that you started to get involved in the library. Good job Sir 👍 💯

2020-11-12 16:54 UTC, larsdouweschuitema commented on src/components/ui-radio.vue
> +                name="funda_radio_input"
For accessibility reasons you need to have a dynamic name property instead of a static string that aligns with the label.

2020-11-12 16:54 UTC, larsdouweschuitema commented on src/components/ui-radio.vue
> +input[type='radio']:disabled ~ label > img {
Maybe you think of a cleaner way to store the data value of the url

2020-11-12 16:54 UTC, larsdouweschuitema commented on src/components/ui-radio.vue
> +    <div>
By wrapping the input in a label you can avoid having to use an extra HTML tag. You can still get the same result visually.

2020-11-12 16:54 UTC, larsdouweschuitema commented on src/components/ui-radio.vue
> +<template>
Instead of having a ui-radio, we should have a ui-input that decides dynamically whether you want to use a radio or a checkbox, so that we avoid having to create two components with similar semantics, styling and behavior.

2020-11-13 05:42 UTC, bartderijk commented on src/components/ui-radio.vue
> +<template>
I'm a bit torn, on one hand I agree the radio and checkbox have a lot in common and on the other hand I feel they have such specific properties that they deserve to be a component on their own. For the sake of simplicity and avoid creating a jack of all kind trades component I'd argue having them separatly for now.

On the second point: I'd like to move forward in the most pragmatic manner possible, getting basic components out there rapidly so we can have a conversation based on what we have instead of what might be. In a past similar project, the team spent over a year theorizing with UX what it should be. In my experience that conversation can go a lot faster if there is a base set of components to begin with, acknowledging that they need more finetuning.

2020-11-13 08:07 UTC, renancarvalho commented on src/components/ui-radio.vue
> +                <img
Indeed Dine!

2020-11-13 08:08 UTC, renancarvalho commented on src/components/ui-radio.vue
> +                name="funda_radio_input"
This is how I make them a radio button group( only one can be selected ). 

could you explain more the relation of it with accessibility?

2020-11-13 08:29 UTC, renancarvalho commented on src/components/ui-radio.vue
> +<template>
It is a direction too, I don't think one is better than the other... just different.
I would rather have it in two components, for simplicity.

2020-11-13 08:29 UTC, renancarvalho commented on src/components/ui-radio.vue
> +input[type='radio']:disabled ~ label > img {
Using variables.

2020-11-13 08:29 UTC, renancarvalho commented on src/components/ui-radio.vue
> +    <div>
Cool

2020-11-13 08:52 UTC, dine approved these changes

2020-11-13 08:52 UTC, dine commented on src/components/ui-radio.vue
> +    --input_checked: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+CiAgPGNpcmNsZSBjeD0iOCIgY3k9IjgiIHI9IjQiIGZpbGw9IiMwMDUxN2YiLz4KPC9z
yay no IE11 support 🎉

2020-11-13 08:53 UTC, renancarvalho commented on src/components/ui-radio.vue
> +    --input_checked: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+CiAgPGNpcmNsZSBjeD0iOCIgY3k9IjgiIHI9IjQiIGZpbGw9IiMwMDUxN2YiLz4KPC9z
Dine 2020 Almost 2021.. what is IE ?

2020-11-13 09:12 UTC, dine approved these changes

2020-11-16 14:40 UTC, renancarvalho commented
Can we move it forward?

2020-11-17 15:36 UTC, sukalas-a commented on src/stories/ui-radio.stories.js
> +        console.log('renan');
onChange log renan 🥇

2020-11-17 15:40 UTC, renancarvalho commented on src/stories/ui-radio.stories.js
> +        console.log('renan');
removing =)

2020-11-18 08:40 UTC, dine submitted a review, later dismissed

2020-11-18 08:43 UTC, renancarvalho commented on src/components/ui-radio.vue
> +                name="funda_radio_input"
@larsdouweschuitema  i think this comment is blocking the merge.

2020-11-20 08:37 UTC, dine commented on src/components/ui-radio.vue
> +import UiLabel from '@/components/ui-label.vue';
We need to import using the relative path `from './ui-label.vue'`

2020-11-20 10:37 UTC, renancarvalho commented on src/components/ui-radio.vue
> +import UiLabel from '@/components/ui-label.vue';
Done!

2020-11-20 13:03 UTC, sukalas-a approved these changes

2020-11-20 13:15 UTC, merged