Spinner component
funda-frontend/ui pull request #143
Opened 2020-11-12 16:28 UTC by bartderijk

2020-11-12 16:46 UTC, larsdouweschuitema requested changes
Added some comments that require some attention, in general: thanks for the good work on this and using tailwind 👍 💯

2020-11-12 16:46 UTC, larsdouweschuitema commented on src/components/ui-spinner.vue
> +        class="spinner animate-spin absolute w-6 h-6 box-border border-3 border-blue-2 rounded-full -mt-3 -ml-3 inset-1/2"
This "spinner" class seems vulnerable to be overwritten. Suggestion: component name ui-spinner

2020-11-12 16:46 UTC, larsdouweschuitema commented on src/components/ui-spinner.vue
> +.spinner {
Can these properties not be done using tailwind?

2020-11-12 16:46 UTC, larsdouweschuitema commented on tailwind.config.js
> +            inset: {
This property name feels confusing when you don't look it up. Can we think of a more descriptive name?

2020-11-12 16:46 UTC, larsdouweschuitema commented on src/components/ui-spinner.vue
> +<template>
Just a general suggestion. Maybe you can think about what types of spinners we are using cross project and how we can determine the type of loading spinner we want to use. 
I would suggest aligning with UX on what spinner patterns we have and what types of properties you need to add, for example:

- Are we using different spinner patterns so that we need to add a property like spinner-type
- Colours
- Sizes

I am not saying you have to implement that all directly, but it might be good having thought about this and seeing what you can be implement versus what we want to implement along the way.

2020-11-12 16:46 UTC, larsdouweschuitema commented on src/components/ui-spinner.vue
> +        class="spinner animate-spin absolute w-6 h-6 box-border border-3 border-blue-2 rounded-full -mt-3 -ml-3 inset-1/2"
I would suggest using dynamic classes for certain classes thinking about how we can easily alter the spinner based on the UX patterns we have. For example: maybe I want an orange spinner, maybe I want to change the size of the spinner.

2020-11-13 04:46 UTC, bartderijk commented on src/components/ui-spinner.vue
> +.spinner {
Single sided borders cannot, unless we use a plugin but that felt like overhead. Also for content I couldn't find anything.

2020-11-13 04:48 UTC, bartderijk commented on tailwind.config.js
> +            inset: {
Inset is what tailwind uses for this, it takes a little getting used to but I think it's not a good idea to deviate from that standard https://tailwindcss.com/docs/top-right-bottom-left#app

2020-11-13 04:49 UTC, bartderijk commented on src/components/ui-spinner.vue
> +<template>
Agreed! I went for the most minimalistic version to start building with, using this as a base we can create more elaborate patterns.

2020-11-13 04:52 UTC, bartderijk commented on src/components/ui-spinner.vue
> +        class="spinner animate-spin absolute w-6 h-6 box-border border-3 border-blue-2 rounded-full -mt-3 -ml-3 inset-1/2"
That's an interesting idea, but for now I'd like to restrict it a bit to prevent a multitude of rainbow colored spinners. I'll introduce size, let's make the component adapt to our needs as we go.

2020-11-13 05:20 UTC, bartderijk commented on src/components/ui-spinner.vue
> +        class="spinner animate-spin absolute w-6 h-6 box-border border-3 border-blue-2 rounded-full -mt-3 -ml-3 inset-1/2"
The color is actually something we would indeed need, given it being used on various colored backgrounds. I'm adding some basic options.

2020-11-13 08:03 UTC, larsdouweschuitema commented on tailwind.config.js
> +            inset: {
I did not know that, It thought it was custom. Never mind this comment then.

2020-11-13 08:05 UTC, larsdouweschuitema approved these changes

2020-11-13 08:10 UTC, merged

2020-11-13 08:24 UTC, dine commented on src/components/ui-spinner.vue
> +    content: '';
We don't need this

2020-11-13 08:24 UTC, dine commented on tailwind.config.js
> +            borderWidth: {
By adding this config here we removed all other border sizes from default tailwind (like `border-2`, `border-4`). Maybe let's use a spinner with 2px border width? Or maybe try the divideWidth: https://tailwindcss.com/docs/divide-width#customizing

2020-11-13 08:24 UTC, dine commented on src/components/ui-spinner.vue
> +    border-right-color: transparent;
https://github.com/tailwindlabs/tailwindcss/pull/560#issuecomment-670045304