Data list
funda-frontend/ui pull request #146
Opened 2020-11-13 09:45 UTC by bartderijk

Added the basics, looking for feedback.

2020-11-17 11:13 UTC, dine commented on src/stories/ui-data-list.stories.js
> +    data: [{ Name: 'Jane Doe' }, { Phone: '020 561 8200' }],
What do you think instead of sending an object we create `<ui-dl>`, `<ui-dt>` and `<ui-dd>` so this way we can use slots and maybe send different things inside? For example, inside the data-list we could use `<ui-icon>` or `<ui-input>`

2020-11-17 11:16 UTC, dine commented on src/stories/ui-data-list.stories.js
> +    data: [{ Name: 'Jane Doe' }, { Phone: '020 561 8200' }],
I'm ok with using like this if we don't feel the need composition for this component. This is a question for everyone @funda-frontend/devs ☝️

2020-11-17 12:51 UTC, renancarvalho commented on src/stories/ui-data-list.stories.js
> +    data: [{ Name: 'Jane Doe' }, { Phone: '020 561 8200' }],
I think it is a great idea @dine, it will make this guy more adaptable.
@bartderijk  let me know if you need help on this.

2020-11-17 13:25 UTC, bartderijk commented on src/stories/ui-data-list.stories.js
> +    data: [{ Name: 'Jane Doe' }, { Phone: '020 561 8200' }],
I like it! All in favor? Speak now or forever hold your peace :)

2020-11-18 08:44 UTC, bartderijk commented on src/stories/ui-data-list.stories.js
> +    data: [{ Name: 'Jane Doe' }, { Phone: '020 561 8200' }],
Done!

2020-11-18 08:47 UTC, dine approved these changes

2020-11-18 08:56 UTC, larsdouweschuitema requested changes

2020-11-18 08:56 UTC, larsdouweschuitema commented on src/components/ui-dd.vue
> +<template>
I would rename these components dd and dt to "data-description" and "data-term" because that is what they are, and it makes it more descriptive.

**Definition and Usage**
The <dd> tag is used to describe a term/name in a description list.
The <dd> tag is used in conjunction with <dl> (defines a description list) and <dt> (defines terms/names).

2020-11-18 09:03 UTC, bartderijk commented on src/components/ui-dd.vue
> +<template>
Nice one!

2020-11-18 09:16 UTC, larsdouweschuitema approved these changes

2020-11-18 09:23 UTC, merged