WIP: Feature/add button component
funda-frontend/ui pull request #20
Opened 2020-08-24 13:24 UTC by larsdouweschuitema

2020-08-24 16:57 UTC, dine reviewed
Since we have semantic release it will only change the version if you use the proper commit messages format: https://github.com/semantic-release/semantic-release#commit-message-format

2020-10-07 08:43 UTC, bartderijk approved these changes

2020-10-07 09:58 UTC, jpsc commented
> Since we have semantic release it will only change the version if you use the proper commit messages format: https://github.com/semantic-release/semantic-release#commit-message-format

Yes, but it's also possible to create that proper message with a squash commit before merging.

2020-10-07 10:01 UTC, jpsc requested changes
I would try to rebase from master and figure out what we can take from this PR that improves the existing button component.

2020-11-11 12:49 UTC, sukalas-a commented on src/components/ui-button.vue
> +<style lang="scss" scoped>
You can now use Tailwind and refactor all these styles

2020-11-11 12:53 UTC, larsdouweschuitema commented
> I would try to rebase from master and figure out what we can take from this PR that improves the existing button component.
That's the plan. Use what you have already made and what can be taken from this. Will keep you posted.

2020-12-03 10:12 UTC, closed without merging