feat(input-id): added support for radio groups using unique ids
funda-frontend/ui pull request #212
Opened 2020-12-14 17:36 UTC by sukalas-a

Added this improvements as I was having issues with the value bindings in Flex-ui. 
Also added a name prop to add radio groups support

2020-12-15 12:54 UTC, larsdouweschuitema requested changes

2020-12-15 12:54 UTC, larsdouweschuitema commented on src/components/ui-radio.vue
> +                :id="(item.label + '_' + id) | trimEmptySpace"
Maybe you can move this to a method that return this as a variable. Also to avoid code duplication for id + for.
Besides that all good 👍

2020-12-15 13:31 UTC, TobbenTM commented on src/components/ui-radio.vue
> +        this.id = this._uid;
`this._uid` is not a public API, and more importantly, doesn't work well with snapshot tests. Is this really the best way?

2020-12-15 13:43 UTC, sukalas-a commented on src/components/ui-radio.vue
> +        this.id = this._uid;
Probably not the best but the simplest.
As far as the testing, It can be mocked right?
As far as the private API point fair enough I guess.
I wanted to avoid making a method that does pseudo UIDs but maybe it's indeed a more solid approach.

2020-12-15 13:48 UTC, TobbenTM commented on src/components/ui-radio.vue
> +        this.id = this._uid;
I think we tried mocking it for some tests, but then we ran into other issues. If you're curious, I think Alexandru should know more.

2020-12-16 13:45 UTC, dine commented on src/components/ui-radio.vue
> +        UUIDs() {
I'd suggest a different name, if we would really need 'uuid'here we could use a package https://en.wikipedia.org/wiki/Universally_unique_identifier

2020-12-16 13:45 UTC, dine commented on src/components/ui-radio.vue
> +        shuffle(string) {
do we need all this?

2020-12-16 14:21 UTC, sukalas-a commented on src/components/ui-radio.vue
> +        shuffle(string) {
I refactored like we discussed. 
To sum up, we agreed that in order to keep the components simple we better let the parent handle the id complexity.

2020-12-16 14:24 UTC, dine approved these changes

2020-12-16 14:30 UTC, merged