feat(modal_close_button): add text option for close modal button
funda-frontend/ui pull request #486
Opened 2021-07-08 09:55 UTC by renancarvalho

Add the possibility to pass any text to replace the default 'X' icon to close the modal.

2021-07-08 09:58 UTC, larsdouweschuitema requested changes

2021-07-08 09:58 UTC, larsdouweschuitema commented on src/components/ui-modal.vue
> +                            'focus:outline-none absolute w-11 h-11 top-1.5 right-1.5 p-2 text-blue-2 hover:text-blue-1',
add focus too, so when you tap to the button it will show the same color as on hover.
removing the outline can remain so you dont have this weird default outline

2021-07-08 10:02 UTC, renancarvalho commented on src/components/ui-modal.vue
> +                            'focus:outline-none absolute w-11 h-11 top-1.5 right-1.5 p-2 text-blue-2 hover:text-blue-1',
done.

2021-07-08 10:09 UTC, dine commented on src/stories/ui-modal.stories.js
> +        closeButtonText: {
Let's add the `closeButtonTitle` too

2021-07-08 10:09 UTC, dine commented on src/stories/ui-modal.stories.js
> +            :closeButtonText="closeButtonText"
Pass the `closeButtonTitle` also and  add both to the `TemplateModalWithContent` below too

2021-07-08 10:09 UTC, dine commented on src/components/ui-modal.vue
> +                        {{ closeButtonText }}
Let's check with @funda-frontend/ux if the padding remains the same when using text here. 
It looks a little bit too close to the right side for me:
https://funda-frontend.github.io/ui/refs/pull/486/merge/?path=/story/layout-modal--modal-default
<img width="145" alt="Screenshot 2021-07-08 at 12 06 15" src="https://user-images.githubusercontent.com/28925/124904079-ec01a380-dfe4-11eb-9d12-2baee0b7a051.png">

2021-07-08 10:15 UTC, renancarvalho commented on src/components/ui-modal.vue
> +                        {{ closeButtonText }}
Can make it pr-3 will look like this 
![image](https://user-images.githubusercontent.com/2653810/124905262-29b2fc00-dfe6-11eb-9a01-9e1b8529c8b4.png)

2021-07-08 10:15 UTC, renancarvalho commented on src/stories/ui-modal.stories.js
> +            :closeButtonText="closeButtonText"
done, next push will have it

2021-07-08 10:15 UTC, renancarvalho commented on src/stories/ui-modal.stories.js
> +        closeButtonText: {
done, next push will have it

2021-07-08 12:12 UTC, jpsc commented
Hello @renancarvalho. While I understand that this PR solves the current limitation I believe that there is a better way to solve this. We currently have 3 properties that are for solving usage of the close button. Maybe we should think about [inversion of control](https://www.youtube.com/watch?v=AiJ8tRRH0f8&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) and giving the consuming user to define what is the close button and what does it do.  In this specific case, it would be to expose the 'close modal event'.

2021-07-08 13:45 UTC, larsdouweschuitema approved these changes

2021-07-09 07:52 UTC, arjanvanrees commented
In the examples in the storybook I notice that the textual 'Close' button is shown as default. I would like to request to change that to the X icon instead. The X icon used the most everywhere on the platform and should be the default in my opinion. Is that still possible?

2021-07-09 09:10 UTC, renancarvalho commented
@arjanvanrees, makes sense. remove the slots from the stories and the X will be there by default.

2021-07-09 09:31 UTC, jpsc submitted a review, later dismissed

2021-07-09 12:54 UTC, dine approved these changes

2021-07-09 12:58 UTC, merged