Feature/acc 132 switch toggle
funda-frontend/ui pull request #636
Opened 2021-11-04 12:19 UTC by ivanasetiawan

In order to make it clear for user how to turn on/off various email settings in the email settings page we want to add a toggle.

2021-11-04 12:27 UTC, bartderijk commented on src/components/ui-switch-toggle.vue
> +            default: '',
Since id is required we can drop the default

2021-11-04 13:17 UTC, daniarsuprianto requested changes

2021-11-04 13:17 UTC, daniarsuprianto commented on package.json
> +    "version": "8.9.0",
the versioning is done automatically based on commit message, so, dont need to change it manually here :)

- [ ] please revert

2021-11-04 13:17 UTC, daniarsuprianto commented on src/stories/ui-switch-toggle.stories.js
> +        '<ui-switch-toggle :checked="true" id="switch-toggle-1" @change="onChange" />',
i assumed `:checked="true"` should be `:checked="checked"` ?

- [ ] update

2021-11-05 08:11 UTC, daniarsuprianto commented on src/stories/ui-switch-toggle.stories.js
> +    title: 'Forms/Checkbox/Switch toggle',
Even though this is a checkbox basically, i'd prefer to have this outside "Checkbox" group because it just feels different to me hahaha.... but i will leave it completely up to you

2021-11-05 08:12 UTC, daniarsuprianto commented
- [ ] Please check final design with rick

2021-11-05 08:12 UTC, daniarsuprianto requested changes
- [ ] Please check final design with rick

2021-11-05 09:13 UTC, ConnorChristensen requested changes

2021-11-05 09:21 UTC, ConnorChristensen commented on src/stories/ui-switch-toggle.stories.js
> +    title: 'Forms/Checkbox/Switch toggle',
If you name this `Switch Toggle` (the same name as the export const), then the storybook sidebar/navigator will look like this
<img width="229" alt="Screen Shot 2021-11-05 at 10 20 41" src="https://user-images.githubusercontent.com/9158517/140487809-0dd129ab-3e7a-4154-848d-897984f8738b.png">
 instead of this
<img width="231" alt="Screen Shot 2021-11-05 at 10 19 46" src="https://user-images.githubusercontent.com/9158517/140487841-cc5ad9ed-3d2c-4f09-ba70-e03352de6156.png">

2021-11-05 09:46 UTC, daniarsuprianto approved these changes

2021-11-05 10:01 UTC, ivanasetiawan commented on src/stories/ui-switch-toggle.stories.js
> +    title: 'Forms/Checkbox/Switch toggle',
I will make Switch Toggle independent.. I think it's more clear like that.

2021-11-05 10:49 UTC, ivanasetiawan commented on src/components/ui-switch-toggle.vue
> +            isChecked: this.checked,
Good catch!

2021-11-05 10:56 UTC, ivanasetiawan commented on src/stories/ui-switch-toggle.stories.js
> +        '<ui-switch-toggle :checked="checked" :id="id" :name="name" @change="onChange""></ui-switch-toggle>',
Personal preference ;)

2021-11-05 13:11 UTC, jpsc requested changes
Hi @ivanasetiawan ,

I think you are missing a few things on the component to make it complete.
- There is no ::active styles (you don't know when the switch is selected)
- There is no keyboard action to activate - According to [this document](https://www.w3.org/TR/wai-aria-1.1/#switch) it needs to behave like a checkbox. 
- For the naming you probably need to choose one of the other. switch-toggle is redundant.
- I'm not sure if possible, but the `v-model` should be the value of checked why do we need both?
- Using the `mounted` lifecycle to set the state means that the initial state when coming from the ssr can be out of sync, anything to avoid this?

2021-11-05 13:12 UTC, jpsc commented
The controls of the story for the checked state don't seem to be working also.

2021-11-05 13:41 UTC, ConnorChristensen commented on src/stories/ui-switch-toggle.stories.js
> +        '<ui-switch-toggle :checked="checked" :id="id" :name="name" @change="onChange""></ui-switch-toggle>',
I think this actually makes an impact (even if it is small) to how stories are written. While we should trust our engineers to be careful, we can also remove the possibility of someone adding an arg and not adding it to the template, or removing a prop from the template and not adjusting the corresponding args. One can certainly overdo the Don't Repeat Yourself principle, I don't think this is one of those cases.

The storybook folks use this in their docs: https://storybook.js.org/docs/vue/get-started/whats-a-story

2021-11-05 13:56 UTC, ivanasetiawan commented
Hi @jpsc 

- There is no ::active styles (you don't know when the switch is selected)
> How do you mean? It's still WIP and I am applying disabled, focused and added checkbox icon based on Rick's design here https://www.figma.com/file/zEYQtitTwXrNgDuMQQPqp9/Toggle-switch?node-id=0%3A1 but there's already a "checked" style

- There is no keyboard action to activate - According to this document it needs to behave like a checkbox.
> On my local, when I hit `space` on my keyboard, it toggles on/off. I will take closely into it and will poke you if I still don't get what you mean

- For the naming you probably need to choose one of the other. switch-toggle is redundant.
> I will rename to Switch, I think it's more clear

- I'm not sure if possible, but the v-model should be the value of checked why do we need both?
> You're right, I actually removed it but haven't pushed 

- Using the mounted lifecycle to set the state means that the initial state when coming from the ssr can be out of sync, anything to avoid this?
> This question also applies to our `ui-accordion`. Have we encountered any issues with that? I am all ears for suggestions on how to approach this based on real case.

2021-11-05 14:13 UTC, jpsc commented
> On my local, when I hit `space` on my keyboard, it toggles on/off. I will take closely into it and will poke you if I still don't get what you mean

That's actually true. It didn't seem to work because of the previous point. There are no ::focus styles so you don't know when you are actually on the element.

2021-11-05 15:31 UTC, ivanasetiawan commented on src/stories/ui-switch-toggle.stories.js
> +        '<ui-switch-toggle :checked="checked" :id="id" :name="name" @change="onChange""></ui-switch-toggle>',
I will take a look at this closely, but `<ui-switch-toggle v-model="$props"></ui-switch-toggle>` is not working.

2021-11-05 16:16 UTC, ivanasetiawan commented on src/components/ui-switch.vue
> +<template>
Make sure the height is at least 44px (per Rick's request)

2021-11-08 12:27 UTC, bartderijk submitted a review, later dismissed

2021-11-08 13:05 UTC, ConnorChristensen requested changes
Please consult the switch design again and make sure all states match the design.

2021-11-08 13:05 UTC, ConnorChristensen commented on src/components/ui-switch.vue
> +            return this.isChecked ? 'bg-blue-3 hover:bg-blue-1' : 'bg-light-1 hover:bg-dark-3';
Hover state can not exist only here. Hover state still needs to be valid when hovering over the circle in the switch.

2021-11-08 13:14 UTC, ivanasetiawan commented on src/components/ui-switch.vue
> +            return this.isChecked ? 'bg-blue-3 hover:bg-blue-1' : 'bg-light-1 hover:bg-dark-3';
Yes can with group-hover. Updated.

2021-11-08 13:36 UTC, ivanasetiawan commented on src/components/ui-switch.vue
> +                    :disabled="disabled"
Thank you for noticing this, I forgot to add the disabled style! Fixed :)

2021-11-08 14:03 UTC, ConnorChristensen commented
* Focus state is not working on toggle
* It would be nice if there was a transition to and from the hover state
* Bonus points if you get the check icon to fade in and out when toggling a icon switch (definitely not a requirement if you are in a rush)

After toggle state is fixed, I will give this an approval.

2021-11-08 15:36 UTC, ivanasetiawan commented
@ConnorChristensen made all the changes: focus + transition + delay check icon.

2021-11-09 08:30 UTC, jpsc commented on package.json
> +        "lint": "eslint --fix --ext \".js,.vue\" --ignore-path .gitignore ."
Not sure why this is part of this PR but it's not a blocker for me.

2021-11-09 08:32 UTC, ivanasetiawan commented on package.json
> +        "lint": "eslint --fix --ext \".js,.vue\" --ignore-path .gitignore ."
Yea I was running lint and thought I could just add it here. I don't think it hurts to leave it here.

2021-11-09 08:33 UTC, ConnorChristensen commented
Looks good! Last thing is all these commits need to be squished into a single commit that adds this new switch component. All of your commits contain the `feat` tag. On release this will add 17 feature bullet points to the changelog that contain mostly fixes, which will be very confusing for future readers.

P.S. If you also want to rebase the branch on master while you are squishing commits, that will be appreciated, but not required.

2021-11-09 08:41 UTC, jpsc submitted a review, later dismissed

2021-11-09 09:43 UTC, ConnorChristensen approved these changes
I see the mouse is still set to a pointer when hovering over a disabled switch, but this is small enough that it is not worth blocking this pull request anymore. If you feel like fixing it and adding a single `fix` commit, that would be appreciated, but we can do it later if need be.

2021-11-09 10:45 UTC, ivanasetiawan commented
Let's do it right! I made the changes with the hover state on disabled and squash the commit.

If you don't like my approach with sprinkling `cursor-pointer` on multiple elements, you can fix it (create a PR for it). 
(I have tested with only putting `cursor-pointer` on the `label` and I didn't like behaviour that's why I took this approach.)

2021-11-09 11:37 UTC, daniarsuprianto approved these changes

2021-11-09 12:19 UTC, ConnorChristensen commented
Looks good to me!

2021-11-09 12:51 UTC, merged