fix(modal): fix fullscreen variant height
funda-frontend/ui pull request #686
Opened 2021-12-06 14:44 UTC by daniarsuprianto

2021-12-07 11:17 UTC, ConnorChristensen requested changes
There appear to still be some visual bugs.

* A modal with long body content can overflow the screen height on short browser windows.
* A modal with long body content with `{ mobileFullScreen: true, variant: 'fullscreen' }` has a weird issue where offscreen content is hidden behind the background when you scroll down.
* It may be worth giving this storybook story to a quality assurance person, as there are a lot of possible variations and I do not think I covered all of them in my review of this pull request.

While we are at it, lets make a few adjustments to the modal story:

* If you are only going to have one story, rename `Default` to `Modal` and it will prevent the story from being a folder with a single story (less clicking to navigate between stories).
* Now that there is no more state in the story that gives a visual indication that the modal actually closes, we should connect actions so we can see that these buttons on the modal actually fire the close event.
  * [This github issue](https://github.com/storybookjs/storybook/discussions/11372) shows how to connect actions.
  * [This storybook documentation page](https://storybook.js.org/docs/vue/essentials/actions) looks like it is showing how to connect actions in the new version 6.4. This might work for our current version but it did not work for me when I gave it a quick try.

2021-12-07 11:17 UTC, ConnorChristensen commented on src/__tests__/ui-modal.test.js
> +    'bg-white shadow-xl relative flex flex-col md:max-h-full';
I think the test needing to be updated to fix a visual bug is an indication that the test is not very flexible and the test was not targeting the right thing in the first place. It is hard to do a visual test through unit testing classes on a component.

This test is effectively a manual implementation of a snapshot, which checks if the output has changed, not if it was correct. I suggest we either remove the visual unit tests, or we implement snapshot testing, and would like to know if others agree with me.

2021-12-07 12:55 UTC, ConnorChristensen submitted a review, later dismissed
I think the body of the modal should always scroll if the screen gets too small. Still seeing some cases where the modal expands past the width of the screen.

2021-12-07 12:55 UTC, ConnorChristensen commented on src/components/ui-modal.vue
> +                        !isFullscreen && !isHalfpage,
This conditional should be a computed value.

2021-12-07 12:55 UTC, ConnorChristensen commented on src/components/ui-modal.vue
> +                            'md:rounded': !isHalfpage,
`isHalfpage ? 'col-span-8' :  'md:rounded'`

2021-12-07 12:55 UTC, ConnorChristensen commented on src/components/ui-modal.vue
> +        isFullscreen() {
I like the rename to make it easy to see that it returns a boolean!

2021-12-08 08:51 UTC, bartderijk commented on src/stories/ui-modal.stories.js
> +                <div :class="{'max-h-96 overflow-auto': longContent && (isDefault || variant === 'small')}">
Another great candidate for a computed prop

2021-12-08 08:52 UTC, bartderijk commented on src/stories/ui-modal.stories.js
>                  <ui-button tone="primary" class="mr-4">Save</ui-button>
Not a change, I know, but `primary` is the default tone so we can omit it here.

2021-12-08 08:55 UTC, bartderijk commented
I missed the context that led up to this PR as I was off for a while. Adding a description, even a tiny one, would be super helpful.

2021-12-08 10:06 UTC, daniarsuprianto commented on src/__tests__/ui-modal.test.js
> +    'bg-white shadow-xl relative flex flex-col md:max-h-full';
i did snapshot tests yeah.. i agree with you that checking the class is not the best way

2021-12-08 10:07 UTC, daniarsuprianto commented on src/components/ui-modal.vue
> +                            'md:rounded': !isHalfpage,
i prefer doing it in different line so that it matches with the rest of the conditional class, just to make it easier more neat imo. so i will leave it how it is if you dont mind :)

2021-12-08 10:10 UTC, daniarsuprianto commented
> A modal with long body content can overflow the screen height on short browser windows.
A modal with long body content with { mobileFullScreen: true, variant: 'fullscreen' } has a weird issue where offscreen content is hidden behind the background when you scroll down.

@bartderijk mostly because of the bugs Connor's found because of the previous breaking change when we decided to remove "customModalClasses" property and make variants instead

2021-12-13 08:51 UTC, larsdouweschuitema commented on src/components/ui-modal.vue
> +                'md:p-9': isFullscreen,
What did you think of the branch I shared earlier?

2021-12-13 09:38 UTC, daniarsuprianto commented on src/components/ui-modal.vue
> +                'md:p-9': isFullscreen,
i like the idea of making everything inside modal as a slot.. however im in doubt if we should have different component like `modal-header` or `modal-footer` or `modal-content`.. i mean, not sure if that's necessary. but im 100% make a slot for the whole content

2021-12-13 10:15 UTC, larsdouweschuitema commented on src/components/ui-modal.vue
> +        isHalfpage() {
Small detail but we talk about "screen" in 1 property and "page" in the other.

2021-12-14 06:01 UTC, daniarsuprianto commented on src/components/ui-modal.vue
> +        isHalfpage() {
if "halfscreen" is more common word, im open to change it. wdyt? is it halfpage or halfscreen?

2021-12-17 08:30 UTC, ivanasetiawan approved these changes
Regarding my comment for `Page` vs. `Screen`, please consider but feel free to use as you see fit :)

2021-12-17 08:30 UTC, ivanasetiawan commented on src/components/ui-modal.vue
> +        isHalfpage() {
This depends on what we wanna show. `Screen` is different than `Page`. 

If we use `halfpage`, I would assume it will be half of the page - so if it's a long page, then this modal will be in the middle, which could be out of the screen.. I'd vote for `halfscreen` IF the purpose is to show in the middle of the screen :)

2021-12-17 10:02 UTC, daniarsuprianto commented on src/components/ui-modal.vue
> +        isHalfpage() {
Discussed with Ivana and we agree to rename this to halfscreen. However, it will be breaking change renaming this, i'd suggest to do it on the next branch about ui-modal to make the content of the modal as a slot. that way we only have 1 version with breaking change instead of 2

2021-12-17 10:08 UTC, daniarsuprianto commented
> I think the body of the modal should always scroll if the screen gets too small. Still seeing some cases where the modal expands past the width of the screen.

it should be handled by adding max-height to the content imo. thing is if user choose not to use the "mobileFullscreen" option, the modal should stay in the middle. we can check "if content is too long, then modal align to top, not in the middle and make it fullscreen instead", but i wouldnt want to add javascript to check the content height to determine the alignment. or they can just use option "mobileFullscreen"

2021-12-17 10:42 UTC, merged